// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercise_tags.sql

package queries

import (
	"context"
)

const addExerciseTag = `-- name: AddExerciseTag :exec
INSERT OR IGNORE INTO exercise_taggings (exercise_id, exercise_tag_id) VALUES (?, ?)
`

type AddExerciseTagParams struct {
	ExerciseID    int64 `json:"exercise_id"`
	ExerciseTagID int64 `json:"exercise_tag_id"`
}

func (q *Queries) AddExerciseTag(ctx context.Context, arg AddExerciseTagParams) error {
	_, err := q.db.ExecContext(ctx, addExerciseTag, arg.ExerciseID, arg.ExerciseTagID)
	return err
}

const clearExerciseTags = `-- name: ClearExerciseTags :exec
DELETE FROM exercise_taggings WHERE exercise_id = ?
`

func (q *Queries) ClearExerciseTags(ctx context.Context, exerciseID int64) error {
	_, err := q.db.ExecContext(ctx, clearExerciseTags, exerciseID)
	return err
}

const createExerciseTag = `-- name: CreateExerciseTag :one
INSERT INTO exercise_tags (name) VALUES (?) RETURNING id, name, created_at
`

func (q *Queries) CreateExerciseTag(ctx context.Context, name string) (ExerciseTag, error) {
	row := q.db.QueryRowContext(ctx, createExerciseTag, name)
	var i ExerciseTag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteExerciseTag = `-- name: DeleteExerciseTag :exec
DELETE FROM exercise_tags WHERE id = ?
`

func (q *Queries) DeleteExerciseTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExerciseTag, id)
	return err
}

const getExerciseTag = `-- name: GetExerciseTag :one
SELECT id, name, created_at FROM exercise_tags WHERE id = ?
`

func (q *Queries) GetExerciseTag(ctx context.Context, id int64) (ExerciseTag, error) {
	row := q.db.QueryRowContext(ctx, getExerciseTag, id)
	var i ExerciseTag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getExerciseTagByName = `-- name: GetExerciseTagByName :one
SELECT id, name, created_at FROM exercise_tags WHERE name = ? COLLATE NOCASE
`

func (q *Queries) GetExerciseTagByName(ctx context.Context, name string) (ExerciseTag, error) {
	row := q.db.QueryRowContext(ctx, getExerciseTagByName, name)
	var i ExerciseTag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTagsForExercise = `-- name: GetTagsForExercise :many
SELECT t.id, t.name, t.created_at
FROM exercise_taggings et
JOIN exercise_tags t ON t.id = et.exercise_tag_id
WHERE et.exercise_id = ?
ORDER BY t.name COLLATE NOCASE
`

func (q *Queries) GetTagsForExercise(ctx context.Context, exerciseID int64) ([]ExerciseTag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForExercise, exerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExerciseTag
	for rows.Next() {
		var i ExerciseTag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllExerciseTagLinks = `-- name: ListAllExerciseTagLinks :many
SELECT et.exercise_id, t.id, t.name, t.created_at
FROM exercise_taggings et
JOIN exercise_tags t ON t.id = et.exercise_tag_id
ORDER BY t.name COLLATE NOCASE
`

type ListAllExerciseTagLinksRow struct {
	ExerciseID int64  `json:"exercise_id"`
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	CreatedAt  string `json:"created_at"`
}

func (q *Queries) ListAllExerciseTagLinks(ctx context.Context) ([]ListAllExerciseTagLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllExerciseTagLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllExerciseTagLinksRow
	for rows.Next() {
		var i ListAllExerciseTagLinksRow
		if err := rows.Scan(
			&i.ExerciseID,
			&i.ID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExerciseTags = `-- name: ListExerciseTags :many
SELECT
  t.id, t.name, t.created_at,
  CAST(COUNT(et.exercise_id) AS INTEGER) AS exercise_count
FROM exercise_tags t
LEFT JOIN exercise_taggings et ON et.exercise_tag_id = t.id
GROUP BY t.id
ORDER BY t.name COLLATE NOCASE
`

type ListExerciseTagsRow struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	CreatedAt     string `json:"created_at"`
	ExerciseCount int64  `json:"exercise_count"`
}

func (q *Queries) ListExerciseTags(ctx context.Context) ([]ListExerciseTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExerciseTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExerciseTagsRow
	for rows.Next() {
		var i ListExerciseTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.ExerciseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercisesByTag = `-- name: ListExercisesByTag :many
SELECT e.id, e.name, e.notes, e.created_at
FROM exercises e
JOIN exercise_taggings et ON et.exercise_id = e.id
WHERE et.exercise_tag_id = ?
ORDER BY e.name
`

func (q *Queries) ListExercisesByTag(ctx context.Context, exerciseTagID int64) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, listExercisesByTag, exerciseTagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
