// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercises.sql

package queries

import (
	"context"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (name, notes) VALUES (?, ?) RETURNING id, name, notes, created_at
`

type CreateExerciseParams struct {
	Name  string `json:"name"`
	Notes string `json:"notes"`
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, createExercise, arg.Name, arg.Notes)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExercise = `-- name: DeleteExercise :exec
DELETE FROM exercises WHERE id = ?
`

func (q *Queries) DeleteExercise(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExercise, id)
	return err
}

const getExercise = `-- name: GetExercise :one
SELECT id, name, notes, created_at FROM exercises WHERE id = ?
`

func (q *Queries) GetExercise(ctx context.Context, id int64) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getExercise, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listExercises = `-- name: ListExercises :many
SELECT id, name, notes, created_at FROM exercises
WHERE name LIKE '%' || ?1 || '%'
ORDER BY name
`

func (q *Queries) ListExercises(ctx context.Context, search *string) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, listExercises, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExercise = `-- name: UpdateExercise :one
UPDATE exercises SET name = ?, notes = ? WHERE id = ? RETURNING id, name, notes, created_at
`

type UpdateExerciseParams struct {
	Name  string `json:"name"`
	Notes string `json:"notes"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, updateExercise, arg.Name, arg.Notes, arg.ID)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
