// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: food_tags.sql

package queries

import (
	"context"
)

const addRecipeFoodTag = `-- name: AddRecipeFoodTag :exec
INSERT OR IGNORE INTO recipe_food_tags (recipe_id, food_tag_id) VALUES (?, ?)
`

type AddRecipeFoodTagParams struct {
	RecipeID  int64 `json:"recipe_id"`
	FoodTagID int64 `json:"food_tag_id"`
}

func (q *Queries) AddRecipeFoodTag(ctx context.Context, arg AddRecipeFoodTagParams) error {
	_, err := q.db.ExecContext(ctx, addRecipeFoodTag, arg.RecipeID, arg.FoodTagID)
	return err
}

const clearRecipeFoodTags = `-- name: ClearRecipeFoodTags :exec
DELETE FROM recipe_food_tags WHERE recipe_id = ?
`

func (q *Queries) ClearRecipeFoodTags(ctx context.Context, recipeID int64) error {
	_, err := q.db.ExecContext(ctx, clearRecipeFoodTags, recipeID)
	return err
}

const createFoodTag = `-- name: CreateFoodTag :one
INSERT INTO food_tags (name) VALUES (?) RETURNING id, name, created_at
`

func (q *Queries) CreateFoodTag(ctx context.Context, name string) (FoodTag, error) {
	row := q.db.QueryRowContext(ctx, createFoodTag, name)
	var i FoodTag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteFoodTag = `-- name: DeleteFoodTag :exec
DELETE FROM food_tags WHERE id = ?
`

func (q *Queries) DeleteFoodTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFoodTag, id)
	return err
}

const getFoodTag = `-- name: GetFoodTag :one
SELECT id, name, created_at FROM food_tags WHERE id = ?
`

func (q *Queries) GetFoodTag(ctx context.Context, id int64) (FoodTag, error) {
	row := q.db.QueryRowContext(ctx, getFoodTag, id)
	var i FoodTag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getFoodTagByName = `-- name: GetFoodTagByName :one
SELECT id, name, created_at FROM food_tags WHERE name = ? COLLATE NOCASE
`

func (q *Queries) GetFoodTagByName(ctx context.Context, name string) (FoodTag, error) {
	row := q.db.QueryRowContext(ctx, getFoodTagByName, name)
	var i FoodTag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getRecipeFoodTags = `-- name: GetRecipeFoodTags :many
SELECT t.id, t.name, t.created_at
FROM recipe_food_tags rt
JOIN food_tags t ON t.id = rt.food_tag_id
WHERE rt.recipe_id = ?
ORDER BY t.name COLLATE NOCASE
`

func (q *Queries) GetRecipeFoodTags(ctx context.Context, recipeID int64) ([]FoodTag, error) {
	rows, err := q.db.QueryContext(ctx, getRecipeFoodTags, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FoodTag
	for rows.Next() {
		var i FoodTag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRecipeFoodTags = `-- name: ListAllRecipeFoodTags :many
SELECT rt.recipe_id, t.id, t.name, t.created_at
FROM recipe_food_tags rt
JOIN food_tags t ON t.id = rt.food_tag_id
ORDER BY t.name COLLATE NOCASE
`

type ListAllRecipeFoodTagsRow struct {
	RecipeID  int64  `json:"recipe_id"`
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) ListAllRecipeFoodTags(ctx context.Context) ([]ListAllRecipeFoodTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllRecipeFoodTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllRecipeFoodTagsRow
	for rows.Next() {
		var i ListAllRecipeFoodTagsRow
		if err := rows.Scan(
			&i.RecipeID,
			&i.ID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoodTags = `-- name: ListFoodTags :many
SELECT
  t.id,
  t.name,
  t.created_at,
  CAST(COUNT(rt.recipe_id) AS INTEGER) AS recipe_count
FROM food_tags t
LEFT JOIN recipe_food_tags rt ON rt.food_tag_id = t.id
GROUP BY t.id
ORDER BY t.name COLLATE NOCASE
`

type ListFoodTagsRow struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	CreatedAt   string `json:"created_at"`
	RecipeCount int64  `json:"recipe_count"`
}

func (q *Queries) ListFoodTags(ctx context.Context) ([]ListFoodTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFoodTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFoodTagsRow
	for rows.Next() {
		var i ListFoodTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.RecipeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipesByFoodTag = `-- name: ListRecipesByFoodTag :many
SELECT
  r.id,
  r.name,
  r.created_at,
  CAST(COALESCE(SUM(i.calories_per_unit * ri.quantity), 0) AS REAL) AS total_calories,
  CAST(COALESCE(SUM(i.protein_per_unit  * ri.quantity), 0) AS REAL) AS total_protein
FROM recipes r
JOIN recipe_food_tags rt        ON rt.recipe_id = r.id
LEFT JOIN recipe_ingredients ri ON ri.recipe_id = r.id
LEFT JOIN ingredients i         ON i.id          = ri.ingredient_id
WHERE rt.food_tag_id = ?
GROUP BY r.id
ORDER BY r.name
`

type ListRecipesByFoodTagRow struct {
	ID            int64   `json:"id"`
	Name          string  `json:"name"`
	CreatedAt     string  `json:"created_at"`
	TotalCalories float64 `json:"total_calories"`
	TotalProtein  float64 `json:"total_protein"`
}

func (q *Queries) ListRecipesByFoodTag(ctx context.Context, foodTagID int64) ([]ListRecipesByFoodTagRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecipesByFoodTag, foodTagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipesByFoodTagRow
	for rows.Next() {
		var i ListRecipesByFoodTagRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.TotalCalories,
			&i.TotalProtein,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
