// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: foods.sql

package queries

import (
	"context"
)

const createFood = `-- name: CreateFood :one
INSERT INTO foods (name, unit, calories_per_unit)
VALUES (?, ?, ?)
RETURNING id, name, unit, calories_per_unit, created_at
`

type CreateFoodParams struct {
	Name            string  `json:"name"`
	Unit            string  `json:"unit"`
	CaloriesPerUnit float64 `json:"calories_per_unit"`
}

func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error) {
	row := q.db.QueryRowContext(ctx, createFood, arg.Name, arg.Unit, arg.CaloriesPerUnit)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.CaloriesPerUnit,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFood = `-- name: DeleteFood :exec
DELETE FROM foods WHERE id = ?
`

func (q *Queries) DeleteFood(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFood, id)
	return err
}

const getFood = `-- name: GetFood :one
SELECT id, name, unit, calories_per_unit, created_at FROM foods WHERE id = ?
`

func (q *Queries) GetFood(ctx context.Context, id int64) (Food, error) {
	row := q.db.QueryRowContext(ctx, getFood, id)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.CaloriesPerUnit,
		&i.CreatedAt,
	)
	return i, err
}

const listFoods = `-- name: ListFoods :many
SELECT id, name, unit, calories_per_unit, created_at FROM foods
WHERE name LIKE '%' || ?1 || '%'
ORDER BY name
`

func (q *Queries) ListFoods(ctx context.Context, search *string) ([]Food, error) {
	rows, err := q.db.QueryContext(ctx, listFoods, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Food
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Unit,
			&i.CaloriesPerUnit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restampLogEntriesForFood = `-- name: RestampLogEntriesForFood :exec
UPDATE log_entries
SET calories_per_unit = ?1,
    calories          = ?1 * quantity
WHERE food_id = ?2
`

type RestampLogEntriesForFoodParams struct {
	CaloriesPerUnit float64 `json:"calories_per_unit"`
	FoodID          *int64  `json:"food_id"`
}

func (q *Queries) RestampLogEntriesForFood(ctx context.Context, arg RestampLogEntriesForFoodParams) error {
	_, err := q.db.ExecContext(ctx, restampLogEntriesForFood, arg.CaloriesPerUnit, arg.FoodID)
	return err
}

const updateFoodCalories = `-- name: UpdateFoodCalories :one
UPDATE foods
SET calories_per_unit = ?
WHERE id = ?
RETURNING id, name, unit, calories_per_unit, created_at
`

type UpdateFoodCaloriesParams struct {
	CaloriesPerUnit float64 `json:"calories_per_unit"`
	ID              int64   `json:"id"`
}

func (q *Queries) UpdateFoodCalories(ctx context.Context, arg UpdateFoodCaloriesParams) (Food, error) {
	row := q.db.QueryRowContext(ctx, updateFoodCalories, arg.CaloriesPerUnit, arg.ID)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.CaloriesPerUnit,
		&i.CreatedAt,
	)
	return i, err
}
