// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingredients.sql

package queries

import (
	"context"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (name, unit, calories_per_unit, protein_per_unit)
VALUES (?, ?, ?, ?)
RETURNING id, name, unit, calories_per_unit, protein_per_unit, created_at
`

type CreateIngredientParams struct {
	Name            string  `json:"name"`
	Unit            string  `json:"unit"`
	CaloriesPerUnit float64 `json:"calories_per_unit"`
	ProteinPerUnit  float64 `json:"protein_per_unit"`
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, createIngredient,
		arg.Name,
		arg.Unit,
		arg.CaloriesPerUnit,
		arg.ProteinPerUnit,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.CaloriesPerUnit,
		&i.ProteinPerUnit,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIngredient = `-- name: DeleteIngredient :exec
DELETE FROM ingredients WHERE id = ?
`

func (q *Queries) DeleteIngredient(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIngredient, id)
	return err
}

const getIngredient = `-- name: GetIngredient :one
SELECT id, name, unit, calories_per_unit, protein_per_unit, created_at FROM ingredients WHERE id = ?
`

func (q *Queries) GetIngredient(ctx context.Context, id int64) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, getIngredient, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.CaloriesPerUnit,
		&i.ProteinPerUnit,
		&i.CreatedAt,
	)
	return i, err
}

const listIngredients = `-- name: ListIngredients :many
SELECT id, name, unit, calories_per_unit, protein_per_unit, created_at FROM ingredients
WHERE name LIKE '%' || ?1 || '%'
ORDER BY name
`

func (q *Queries) ListIngredients(ctx context.Context, search *string) ([]Ingredient, error) {
	rows, err := q.db.QueryContext(ctx, listIngredients, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Unit,
			&i.CaloriesPerUnit,
			&i.ProteinPerUnit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restampLogEntriesForIngredient = `-- name: RestampLogEntriesForIngredient :exec
UPDATE log_entries
SET calories_per_unit = ?1,
    calories          = ?1 * quantity,
    protein_per_unit  = ?2,
    protein           = ?2 * quantity
WHERE ingredient_id = ?3
`

type RestampLogEntriesForIngredientParams struct {
	CaloriesPerUnit float64 `json:"calories_per_unit"`
	ProteinPerUnit  float64 `json:"protein_per_unit"`
	IngredientID    *int64  `json:"ingredient_id"`
}

func (q *Queries) RestampLogEntriesForIngredient(ctx context.Context, arg RestampLogEntriesForIngredientParams) error {
	_, err := q.db.ExecContext(ctx, restampLogEntriesForIngredient, arg.CaloriesPerUnit, arg.ProteinPerUnit, arg.IngredientID)
	return err
}

const updateIngredientNutrition = `-- name: UpdateIngredientNutrition :one
UPDATE ingredients
SET calories_per_unit = ?,
    protein_per_unit  = ?
WHERE id = ?
RETURNING id, name, unit, calories_per_unit, protein_per_unit, created_at
`

type UpdateIngredientNutritionParams struct {
	CaloriesPerUnit float64 `json:"calories_per_unit"`
	ProteinPerUnit  float64 `json:"protein_per_unit"`
	ID              int64   `json:"id"`
}

func (q *Queries) UpdateIngredientNutrition(ctx context.Context, arg UpdateIngredientNutritionParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, updateIngredientNutrition, arg.CaloriesPerUnit, arg.ProteinPerUnit, arg.ID)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.CaloriesPerUnit,
		&i.ProteinPerUnit,
		&i.CreatedAt,
	)
	return i, err
}
