// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: log.sql

package queries

import (
	"context"
)

const addLogEntry = `-- name: AddLogEntry :one
INSERT INTO log_entries
  (user_id, ingredient_id, date, ingredient_name, ingredient_unit,
   calories_per_unit, protein_per_unit,
   quantity, calories, protein,
   recipe_group_id, source_recipe_name, source_recipe_servings)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, ingredient_id, date, ingredient_name, ingredient_unit, calories_per_unit, protein_per_unit, quantity, calories, protein, recipe_group_id, source_recipe_name, source_recipe_servings
`

type AddLogEntryParams struct {
	UserID               int64    `json:"user_id"`
	IngredientID         *int64   `json:"ingredient_id"`
	Date                 string   `json:"date"`
	IngredientName       string   `json:"ingredient_name"`
	IngredientUnit       string   `json:"ingredient_unit"`
	CaloriesPerUnit      float64  `json:"calories_per_unit"`
	ProteinPerUnit       float64  `json:"protein_per_unit"`
	Quantity             float64  `json:"quantity"`
	Calories             float64  `json:"calories"`
	Protein              float64  `json:"protein"`
	RecipeGroupID        *int64   `json:"recipe_group_id"`
	SourceRecipeName     *string  `json:"source_recipe_name"`
	SourceRecipeServings *float64 `json:"source_recipe_servings"`
}

func (q *Queries) AddLogEntry(ctx context.Context, arg AddLogEntryParams) (LogEntry, error) {
	row := q.db.QueryRowContext(ctx, addLogEntry,
		arg.UserID,
		arg.IngredientID,
		arg.Date,
		arg.IngredientName,
		arg.IngredientUnit,
		arg.CaloriesPerUnit,
		arg.ProteinPerUnit,
		arg.Quantity,
		arg.Calories,
		arg.Protein,
		arg.RecipeGroupID,
		arg.SourceRecipeName,
		arg.SourceRecipeServings,
	)
	var i LogEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IngredientID,
		&i.Date,
		&i.IngredientName,
		&i.IngredientUnit,
		&i.CaloriesPerUnit,
		&i.ProteinPerUnit,
		&i.Quantity,
		&i.Calories,
		&i.Protein,
		&i.RecipeGroupID,
		&i.SourceRecipeName,
		&i.SourceRecipeServings,
	)
	return i, err
}

const deleteLogEntriesByGroup = `-- name: DeleteLogEntriesByGroup :exec
DELETE FROM log_entries
WHERE user_id = ?1
  AND date    = ?2
  AND recipe_group_id = ?3
`

type DeleteLogEntriesByGroupParams struct {
	UserID        int64  `json:"user_id"`
	Date          string `json:"date"`
	RecipeGroupID *int64 `json:"recipe_group_id"`
}

func (q *Queries) DeleteLogEntriesByGroup(ctx context.Context, arg DeleteLogEntriesByGroupParams) error {
	_, err := q.db.ExecContext(ctx, deleteLogEntriesByGroup, arg.UserID, arg.Date, arg.RecipeGroupID)
	return err
}

const deleteLogEntry = `-- name: DeleteLogEntry :exec
DELETE FROM log_entries WHERE id = ? AND user_id = ?
`

type DeleteLogEntryParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteLogEntry(ctx context.Context, arg DeleteLogEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteLogEntry, arg.ID, arg.UserID)
	return err
}

const getLogHistory = `-- name: GetLogHistory :many
SELECT id, user_id, ingredient_id, date, ingredient_name, ingredient_unit, calories_per_unit, protein_per_unit, quantity, calories, protein, recipe_group_id, source_recipe_name, source_recipe_servings FROM log_entries
WHERE user_id = ?
ORDER BY date DESC, id
`

func (q *Queries) GetLogHistory(ctx context.Context, userID int64) ([]LogEntry, error) {
	rows, err := q.db.QueryContext(ctx, getLogHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogEntry
	for rows.Next() {
		var i LogEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IngredientID,
			&i.Date,
			&i.IngredientName,
			&i.IngredientUnit,
			&i.CaloriesPerUnit,
			&i.ProteinPerUnit,
			&i.Quantity,
			&i.Calories,
			&i.Protein,
			&i.RecipeGroupID,
			&i.SourceRecipeName,
			&i.SourceRecipeServings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumNutritionByDateRange = `-- name: SumNutritionByDateRange :many
SELECT
  date,
  CAST(COALESCE(SUM(calories), 0) AS REAL) AS total_calories,
  CAST(COALESCE(SUM(protein),  0) AS REAL) AS total_protein
FROM log_entries
WHERE user_id = ?1
  AND date >= ?2
  AND date <= ?3
GROUP BY date
ORDER BY date
`

type SumNutritionByDateRangeParams struct {
	UserID   int64  `json:"user_id"`
	FromDate string `json:"from_date"`
	ToDate   string `json:"to_date"`
}

type SumNutritionByDateRangeRow struct {
	Date          string  `json:"date"`
	TotalCalories float64 `json:"total_calories"`
	TotalProtein  float64 `json:"total_protein"`
}

func (q *Queries) SumNutritionByDateRange(ctx context.Context, arg SumNutritionByDateRangeParams) ([]SumNutritionByDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, sumNutritionByDateRange, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumNutritionByDateRangeRow
	for rows.Next() {
		var i SumNutritionByDateRangeRow
		if err := rows.Scan(&i.Date, &i.TotalCalories, &i.TotalProtein); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
