// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: log.sql

package queries

import (
	"context"
)

const addLogEntry = `-- name: AddLogEntry :one
INSERT INTO log_entries
  (user_id, food_id, date, food_name, food_unit, calories_per_unit, quantity, calories,
   source_recipe_id, source_recipe_name)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, food_id, date, food_name, food_unit, calories_per_unit, quantity, calories, source_recipe_id, source_recipe_name
`

type AddLogEntryParams struct {
	UserID           int64   `json:"user_id"`
	FoodID           *int64  `json:"food_id"`
	Date             string  `json:"date"`
	FoodName         string  `json:"food_name"`
	FoodUnit         string  `json:"food_unit"`
	CaloriesPerUnit  float64 `json:"calories_per_unit"`
	Quantity         float64 `json:"quantity"`
	Calories         float64 `json:"calories"`
	SourceRecipeID   *int64  `json:"source_recipe_id"`
	SourceRecipeName *string `json:"source_recipe_name"`
}

func (q *Queries) AddLogEntry(ctx context.Context, arg AddLogEntryParams) (LogEntry, error) {
	row := q.db.QueryRowContext(ctx, addLogEntry,
		arg.UserID,
		arg.FoodID,
		arg.Date,
		arg.FoodName,
		arg.FoodUnit,
		arg.CaloriesPerUnit,
		arg.Quantity,
		arg.Calories,
		arg.SourceRecipeID,
		arg.SourceRecipeName,
	)
	var i LogEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FoodID,
		&i.Date,
		&i.FoodName,
		&i.FoodUnit,
		&i.CaloriesPerUnit,
		&i.Quantity,
		&i.Calories,
		&i.SourceRecipeID,
		&i.SourceRecipeName,
	)
	return i, err
}

const deleteLogEntriesByRecipe = `-- name: DeleteLogEntriesByRecipe :exec
DELETE FROM log_entries
WHERE user_id = ?1
  AND date    = ?2
  AND source_recipe_id = ?3
`

type DeleteLogEntriesByRecipeParams struct {
	UserID         int64  `json:"user_id"`
	Date           string `json:"date"`
	SourceRecipeID *int64 `json:"source_recipe_id"`
}

func (q *Queries) DeleteLogEntriesByRecipe(ctx context.Context, arg DeleteLogEntriesByRecipeParams) error {
	_, err := q.db.ExecContext(ctx, deleteLogEntriesByRecipe, arg.UserID, arg.Date, arg.SourceRecipeID)
	return err
}

const deleteLogEntry = `-- name: DeleteLogEntry :exec
DELETE FROM log_entries WHERE id = ? AND user_id = ?
`

type DeleteLogEntryParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteLogEntry(ctx context.Context, arg DeleteLogEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteLogEntry, arg.ID, arg.UserID)
	return err
}

const getLogForDate = `-- name: GetLogForDate :many
SELECT id, user_id, food_id, date, food_name, food_unit, calories_per_unit, quantity, calories, source_recipe_id, source_recipe_name FROM log_entries
WHERE user_id = ? AND date = ?
ORDER BY id
`

type GetLogForDateParams struct {
	UserID int64  `json:"user_id"`
	Date   string `json:"date"`
}

func (q *Queries) GetLogForDate(ctx context.Context, arg GetLogForDateParams) ([]LogEntry, error) {
	rows, err := q.db.QueryContext(ctx, getLogForDate, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogEntry
	for rows.Next() {
		var i LogEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FoodID,
			&i.Date,
			&i.FoodName,
			&i.FoodUnit,
			&i.CaloriesPerUnit,
			&i.Quantity,
			&i.Calories,
			&i.SourceRecipeID,
			&i.SourceRecipeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentLoggedFoods = `-- name: GetRecentLoggedFoods :many
SELECT
  le.food_name,
  le.food_unit,
  le.calories_per_unit,
  le.food_id,
  le.quantity AS last_quantity
FROM log_entries le
INNER JOIN (
  SELECT inner_le.food_name AS fn, MAX(inner_le.id) AS max_id
  FROM log_entries inner_le
  WHERE inner_le.user_id = ?1
    AND inner_le.source_recipe_id IS NULL
  GROUP BY inner_le.food_name
) latest ON le.id = latest.max_id
ORDER BY le.id DESC
LIMIT 20
`

type GetRecentLoggedFoodsRow struct {
	FoodName        string  `json:"food_name"`
	FoodUnit        string  `json:"food_unit"`
	CaloriesPerUnit float64 `json:"calories_per_unit"`
	FoodID          *int64  `json:"food_id"`
	LastQuantity    float64 `json:"last_quantity"`
}

func (q *Queries) GetRecentLoggedFoods(ctx context.Context, userID int64) ([]GetRecentLoggedFoodsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentLoggedFoods, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentLoggedFoodsRow
	for rows.Next() {
		var i GetRecentLoggedFoodsRow
		if err := rows.Scan(
			&i.FoodName,
			&i.FoodUnit,
			&i.CaloriesPerUnit,
			&i.FoodID,
			&i.LastQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumCaloriesByDateRange = `-- name: SumCaloriesByDateRange :many
SELECT
  date,
  CAST(COALESCE(SUM(calories), 0) AS REAL) AS total_calories
FROM log_entries
WHERE user_id = ?1
  AND date >= ?2
  AND date <= ?3
GROUP BY date
ORDER BY date
`

type SumCaloriesByDateRangeParams struct {
	UserID   int64  `json:"user_id"`
	FromDate string `json:"from_date"`
	ToDate   string `json:"to_date"`
}

type SumCaloriesByDateRangeRow struct {
	Date          string  `json:"date"`
	TotalCalories float64 `json:"total_calories"`
}

func (q *Queries) SumCaloriesByDateRange(ctx context.Context, arg SumCaloriesByDateRangeParams) ([]SumCaloriesByDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, sumCaloriesByDateRange, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumCaloriesByDateRangeRow
	for rows.Next() {
		var i SumCaloriesByDateRangeRow
		if err := rows.Scan(&i.Date, &i.TotalCalories); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
