// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package queries

import (
	"context"
)

const getMetricsForDate = `-- name: GetMetricsForDate :one
SELECT id, user_id, date, weight, steps, target_calories FROM daily_metrics
WHERE user_id = ? AND date = ?
`

type GetMetricsForDateParams struct {
	UserID int64  `json:"user_id"`
	Date   string `json:"date"`
}

func (q *Queries) GetMetricsForDate(ctx context.Context, arg GetMetricsForDateParams) (DailyMetric, error) {
	row := q.db.QueryRowContext(ctx, getMetricsForDate, arg.UserID, arg.Date)
	var i DailyMetric
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Weight,
		&i.Steps,
		&i.TargetCalories,
	)
	return i, err
}

const getMetricsRange = `-- name: GetMetricsRange :many
SELECT id, user_id, date, weight, steps, target_calories FROM daily_metrics
WHERE user_id = ?1
  AND date >= ?2
  AND date <= ?3
ORDER BY date
`

type GetMetricsRangeParams struct {
	UserID   int64  `json:"user_id"`
	FromDate string `json:"from_date"`
	ToDate   string `json:"to_date"`
}

func (q *Queries) GetMetricsRange(ctx context.Context, arg GetMetricsRangeParams) ([]DailyMetric, error) {
	rows, err := q.db.QueryContext(ctx, getMetricsRange, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyMetric
	for rows.Next() {
		var i DailyMetric
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Weight,
			&i.Steps,
			&i.TargetCalories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodaySummary = `-- name: GetTodaySummary :one
SELECT
  CAST(COALESCE((SELECT SUM(le.calories) FROM log_entries le
            WHERE le.user_id = ?1 AND le.date = date('now')), 0) AS REAL) AS consumed,
  CAST(COALESCE((SELECT dm.target_calories FROM daily_metrics dm
            WHERE dm.user_id = ?1 AND dm.date = date('now')), 0) AS INTEGER) AS target
`

type GetTodaySummaryRow struct {
	Consumed float64 `json:"consumed"`
	Target   int64   `json:"target"`
}

func (q *Queries) GetTodaySummary(ctx context.Context, userID int64) (GetTodaySummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getTodaySummary, userID)
	var i GetTodaySummaryRow
	err := row.Scan(&i.Consumed, &i.Target)
	return i, err
}

const upsertMetrics = `-- name: UpsertMetrics :one
INSERT INTO daily_metrics (user_id, date, weight, steps, target_calories)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(user_id, date) DO UPDATE SET
  weight          = excluded.weight,
  steps           = excluded.steps,
  target_calories = excluded.target_calories
RETURNING id, user_id, date, weight, steps, target_calories
`

type UpsertMetricsParams struct {
	UserID         int64    `json:"user_id"`
	Date           string   `json:"date"`
	Weight         *float64 `json:"weight"`
	Steps          *int64   `json:"steps"`
	TargetCalories *int64   `json:"target_calories"`
}

func (q *Queries) UpsertMetrics(ctx context.Context, arg UpsertMetricsParams) (DailyMetric, error) {
	row := q.db.QueryRowContext(ctx, upsertMetrics,
		arg.UserID,
		arg.Date,
		arg.Weight,
		arg.Steps,
		arg.TargetCalories,
	)
	var i DailyMetric
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Weight,
		&i.Steps,
		&i.TargetCalories,
	)
	return i, err
}
