// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

type DailyMetric struct {
	ID     int64    `json:"id"`
	UserID int64    `json:"user_id"`
	Date   string   `json:"date"`
	Weight *float64 `json:"weight"`
	Steps  *int64   `json:"steps"`
}

type Food struct {
	ID              int64   `json:"id"`
	Name            string  `json:"name"`
	Unit            string  `json:"unit"`
	CaloriesPerUnit float64 `json:"calories_per_unit"`
	ProteinPerUnit  float64 `json:"protein_per_unit"`
	CreatedAt       string  `json:"created_at"`
}

type LogEntry struct {
	ID                   int64    `json:"id"`
	UserID               int64    `json:"user_id"`
	FoodID               *int64   `json:"food_id"`
	Date                 string   `json:"date"`
	FoodName             string   `json:"food_name"`
	FoodUnit             string   `json:"food_unit"`
	CaloriesPerUnit      float64  `json:"calories_per_unit"`
	ProteinPerUnit       float64  `json:"protein_per_unit"`
	Quantity             float64  `json:"quantity"`
	Calories             float64  `json:"calories"`
	Protein              float64  `json:"protein"`
	SourceRecipeID       *int64   `json:"source_recipe_id"`
	SourceRecipeName     *string  `json:"source_recipe_name"`
	SourceRecipeServings *float64 `json:"source_recipe_servings"`
}

type Recipe struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

type RecipeIngredient struct {
	ID       int64   `json:"id"`
	RecipeID int64   `json:"recipe_id"`
	FoodID   int64   `json:"food_id"`
	Quantity float64 `json:"quantity"`
}

type User struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	Avatar         string `json:"avatar"`
	TargetCalories int64  `json:"target_calories"`
	TargetProtein  int64  `json:"target_protein"`
	CreatedAt      string `json:"created_at"`
}
