// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package queries

import (
	"context"
)

const addRecipeIngredient = `-- name: AddRecipeIngredient :one
INSERT INTO recipe_ingredients (recipe_id, food_id, quantity)
VALUES (?, ?, ?)
RETURNING id, recipe_id, food_id, quantity
`

type AddRecipeIngredientParams struct {
	RecipeID int64   `json:"recipe_id"`
	FoodID   int64   `json:"food_id"`
	Quantity float64 `json:"quantity"`
}

func (q *Queries) AddRecipeIngredient(ctx context.Context, arg AddRecipeIngredientParams) (RecipeIngredient, error) {
	row := q.db.QueryRowContext(ctx, addRecipeIngredient, arg.RecipeID, arg.FoodID, arg.Quantity)
	var i RecipeIngredient
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.FoodID,
		&i.Quantity,
	)
	return i, err
}

const clearRecipeIngredients = `-- name: ClearRecipeIngredients :exec
DELETE FROM recipe_ingredients WHERE recipe_id = ?
`

func (q *Queries) ClearRecipeIngredients(ctx context.Context, recipeID int64) error {
	_, err := q.db.ExecContext(ctx, clearRecipeIngredients, recipeID)
	return err
}

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (name) VALUES (?) RETURNING id, name, created_at
`

func (q *Queries) CreateRecipe(ctx context.Context, name string) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, createRecipe, name)
	var i Recipe
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteRecipe = `-- name: DeleteRecipe :exec
DELETE FROM recipes WHERE id = ?
`

func (q *Queries) DeleteRecipe(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecipe, id)
	return err
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, name, created_at FROM recipes WHERE id = ?
`

func (q *Queries) GetRecipe(ctx context.Context, id int64) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipe, id)
	var i Recipe
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getRecipeIngredients = `-- name: GetRecipeIngredients :many
SELECT
  ri.id,
  ri.recipe_id,
  ri.food_id,
  ri.quantity,
  f.name              AS food_name,
  f.unit              AS food_unit,
  f.calories_per_unit AS calories_per_unit
FROM recipe_ingredients ri
JOIN foods f ON f.id = ri.food_id
WHERE ri.recipe_id = ?
ORDER BY ri.id
`

type GetRecipeIngredientsRow struct {
	ID              int64   `json:"id"`
	RecipeID        int64   `json:"recipe_id"`
	FoodID          int64   `json:"food_id"`
	Quantity        float64 `json:"quantity"`
	FoodName        string  `json:"food_name"`
	FoodUnit        string  `json:"food_unit"`
	CaloriesPerUnit float64 `json:"calories_per_unit"`
}

func (q *Queries) GetRecipeIngredients(ctx context.Context, recipeID int64) ([]GetRecipeIngredientsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecipeIngredients, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecipeIngredientsRow
	for rows.Next() {
		var i GetRecipeIngredientsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.FoodID,
			&i.Quantity,
			&i.FoodName,
			&i.FoodUnit,
			&i.CaloriesPerUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many
SELECT
  r.id,
  r.name,
  r.created_at,
  CAST(COALESCE(SUM(f.calories_per_unit * ri.quantity), 0) AS REAL) AS total_calories
FROM recipes r
LEFT JOIN recipe_ingredients ri ON ri.recipe_id = r.id
LEFT JOIN foods f               ON f.id          = ri.food_id
WHERE r.name LIKE '%' || ?1 || '%'
GROUP BY r.id
ORDER BY r.name
`

type ListRecipesRow struct {
	ID            int64   `json:"id"`
	Name          string  `json:"name"`
	CreatedAt     string  `json:"created_at"`
	TotalCalories float64 `json:"total_calories"`
}

func (q *Queries) ListRecipes(ctx context.Context, search *string) ([]ListRecipesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecipes, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipesRow
	for rows.Next() {
		var i ListRecipesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.TotalCalories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipeName = `-- name: UpdateRecipeName :exec
UPDATE recipes SET name = ? WHERE id = ?
`

type UpdateRecipeNameParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateRecipeName(ctx context.Context, arg UpdateRecipeNameParams) error {
	_, err := q.db.ExecContext(ctx, updateRecipeName, arg.Name, arg.ID)
	return err
}
