// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sets.sql

package queries

import (
	"context"
)

const addSet = `-- name: AddSet :one
INSERT INTO exercise_sets (user_id, exercise_id, exercise_name, date, weight, reps, unit)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, exercise_id, exercise_name, date, weight, reps, unit
`

type AddSetParams struct {
	UserID       int64   `json:"user_id"`
	ExerciseID   *int64  `json:"exercise_id"`
	ExerciseName string  `json:"exercise_name"`
	Date         string  `json:"date"`
	Weight       float64 `json:"weight"`
	Reps         int64   `json:"reps"`
	Unit         string  `json:"unit"`
}

func (q *Queries) AddSet(ctx context.Context, arg AddSetParams) (ExerciseSet, error) {
	row := q.db.QueryRowContext(ctx, addSet,
		arg.UserID,
		arg.ExerciseID,
		arg.ExerciseName,
		arg.Date,
		arg.Weight,
		arg.Reps,
		arg.Unit,
	)
	var i ExerciseSet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExerciseID,
		&i.ExerciseName,
		&i.Date,
		&i.Weight,
		&i.Reps,
		&i.Unit,
	)
	return i, err
}

const deleteSet = `-- name: DeleteSet :exec
DELETE FROM exercise_sets WHERE id = ? AND user_id = ?
`

type DeleteSetParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteSet(ctx context.Context, arg DeleteSetParams) error {
	_, err := q.db.ExecContext(ctx, deleteSet, arg.ID, arg.UserID)
	return err
}

const getLastSetsForExercise = `-- name: GetLastSetsForExercise :many
SELECT es.id, es.user_id, es.exercise_id, es.exercise_name, es.date, es.weight, es.reps, es.unit FROM exercise_sets es
WHERE es.user_id = ?1
  AND es.exercise_id = ?2
  AND es.date = (
    SELECT MAX(inner_es.date) FROM exercise_sets inner_es
    WHERE inner_es.user_id = ?1 AND inner_es.exercise_id = ?2
  )
ORDER BY es.id
`

type GetLastSetsForExerciseParams struct {
	UserID     int64  `json:"user_id"`
	ExerciseID *int64 `json:"exercise_id"`
}

func (q *Queries) GetLastSetsForExercise(ctx context.Context, arg GetLastSetsForExerciseParams) ([]ExerciseSet, error) {
	rows, err := q.db.QueryContext(ctx, getLastSetsForExercise, arg.UserID, arg.ExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExerciseSet
	for rows.Next() {
		var i ExerciseSet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.Date,
			&i.Weight,
			&i.Reps,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProgressSets = `-- name: GetProgressSets :many
SELECT s.exercise_id, s.exercise_name, s.date, s.weight, s.reps
FROM exercise_sets s
WHERE s.user_id = ?1
  AND s.date >= ?2
  AND s.date <= ?3
ORDER BY s.exercise_name COLLATE NOCASE, s.date, s.id
`

type GetProgressSetsParams struct {
	UserID   int64  `json:"user_id"`
	FromDate string `json:"from_date"`
	ToDate   string `json:"to_date"`
}

type GetProgressSetsRow struct {
	ExerciseID   *int64  `json:"exercise_id"`
	ExerciseName string  `json:"exercise_name"`
	Date         string  `json:"date"`
	Weight       float64 `json:"weight"`
	Reps         int64   `json:"reps"`
}

func (q *Queries) GetProgressSets(ctx context.Context, arg GetProgressSetsParams) ([]GetProgressSetsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProgressSets, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProgressSetsRow
	for rows.Next() {
		var i GetProgressSetsRow
		if err := rows.Scan(
			&i.ExerciseID,
			&i.ExerciseName,
			&i.Date,
			&i.Weight,
			&i.Reps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetHistory = `-- name: GetSetHistory :many
SELECT id, user_id, exercise_id, exercise_name, date, weight, reps, unit FROM exercise_sets
WHERE user_id = ?
ORDER BY date DESC, id DESC
`

func (q *Queries) GetSetHistory(ctx context.Context, userID int64) ([]ExerciseSet, error) {
	rows, err := q.db.QueryContext(ctx, getSetHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExerciseSet
	for rows.Next() {
		var i ExerciseSet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.Date,
			&i.Weight,
			&i.Reps,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSet = `-- name: UpdateSet :one
UPDATE exercise_sets SET weight = ?, reps = ?
WHERE id = ? AND user_id = ?
RETURNING id, user_id, exercise_id, exercise_name, date, weight, reps, unit
`

type UpdateSetParams struct {
	Weight float64 `json:"weight"`
	Reps   int64   `json:"reps"`
	ID     int64   `json:"id"`
	UserID int64   `json:"user_id"`
}

func (q *Queries) UpdateSet(ctx context.Context, arg UpdateSetParams) (ExerciseSet, error) {
	row := q.db.QueryRowContext(ctx, updateSet,
		arg.Weight,
		arg.Reps,
		arg.ID,
		arg.UserID,
	)
	var i ExerciseSet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExerciseID,
		&i.ExerciseName,
		&i.Date,
		&i.Weight,
		&i.Reps,
		&i.Unit,
	)
	return i, err
}
