// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package queries

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, avatar, target_calories, target_protein)
VALUES (?, ?, ?, ?)
RETURNING id, name, avatar, target_calories, target_protein, created_at
`

type CreateUserParams struct {
	Name           string `json:"name"`
	Avatar         string `json:"avatar"`
	TargetCalories int64  `json:"target_calories"`
	TargetProtein  int64  `json:"target_protein"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Avatar,
		arg.TargetCalories,
		arg.TargetProtein,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.TargetCalories,
		&i.TargetProtein,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, avatar, target_calories, target_protein, created_at FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.TargetCalories,
		&i.TargetProtein,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, avatar, target_calories, target_protein, created_at FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Avatar,
			&i.TargetCalories,
			&i.TargetProtein,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name            = ?,
    target_calories = ?,
    target_protein  = ?
WHERE id = ?
RETURNING id, name, avatar, target_calories, target_protein, created_at
`

type UpdateUserParams struct {
	Name           string `json:"name"`
	TargetCalories int64  `json:"target_calories"`
	TargetProtein  int64  `json:"target_protein"`
	ID             int64  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.TargetCalories,
		arg.TargetProtein,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.TargetCalories,
		&i.TargetProtein,
		&i.CreatedAt,
	)
	return i, err
}
